// ─────────────────────────────────────────────────────────────────────────────
// PathForge — Learning Resources Database
// Curated courses from Coursera, edX, Udemy, YouTube & Khan Academy
// for every skill across all 26 career paths.
// ─────────────────────────────────────────────────────────────────────────────

export type Platform =
  | "Coursera"
  | "edX"
  | "Udemy"
  | "YouTube"
  | "Khan Academy"
  | "LinkedIn Learning"
  | "Other";

export interface Course {
  title: string;
  provider: string; // university / instructor name
  platform: Platform;
  url: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  duration: string;
  free: boolean;
  badge?: "Popular" | "Top Rated" | "Free" | "Beginner Friendly" | "Certification";
}

export interface SkillResources {
  description: string;
  courses: Course[];
}

export const SKILL_RESOURCES: Record<string, SkillResources> = {
  // ── IT Skills ─────────────────────────────────────────────────────────────

  Python: {
    description:
      "Python is a versatile, beginner-friendly language used across data science, AI, web development, and automation.",
    courses: [
      {
        title: "Python for Everybody Specialization",
        provider: "University of Michigan",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/python",
        level: "Beginner",
        duration: "8 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "100 Days of Code: The Complete Python Pro Bootcamp",
        provider: "Angela Yu",
        platform: "Udemy",
        url: "https://www.udemy.com/course/100-days-of-code/",
        level: "Beginner",
        duration: "60 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Introduction to Computer Science and Programming Using Python",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/learn/python/massachusetts-institute-of-technology-introduction-to-computer-science-and-programming-using-python",
        level: "Beginner",
        duration: "9 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Python Full Course for Beginners",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=rfscVS0vtbw",
        level: "Beginner",
        duration: "4.5 hours",
        free: true,
        badge: "Beginner Friendly",
      },
      {
        title: "Python 3 Programming Specialization",
        provider: "University of Michigan",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/python-3-programming",
        level: "Intermediate",
        duration: "5 months",
        free: false,
      },
    ],
  },

  SQL: {
    description:
      "SQL is the standard language for managing and querying relational databases, essential for data roles.",
    courses: [
      {
        title: "SQL for Data Science",
        provider: "UC Davis",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/sql-for-data-science",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "The Complete SQL Bootcamp: Go from Zero to Hero",
        provider: "Jose Portilla",
        platform: "Udemy",
        url: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
        level: "Beginner",
        duration: "9 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Databases and SQL for Data Science with Python",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/sql-data-science",
        level: "Beginner",
        duration: "6 weeks",
        free: false,
      },
      {
        title: "SQL Tutorial – Full Database Course for Beginners",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=HXV3zeQKqGY",
        level: "Beginner",
        duration: "4 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Querying with Transact-SQL",
        provider: "Microsoft",
        platform: "edX",
        url: "https://www.edx.org/learn/sql/microsoft-querying-with-transact-sql",
        level: "Intermediate",
        duration: "6 weeks",
        free: true,
        badge: "Free",
      },
    ],
  },

  Statistics: {
    description:
      "Statistics forms the mathematical backbone of data science, machine learning, and financial analysis.",
    courses: [
      {
        title: "Statistics with Python Specialization",
        provider: "University of Michigan",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/statistics-with-python",
        level: "Intermediate",
        duration: "5 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Statistics and Probability",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/math/statistics-probability",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Statistics for Data Science and Business Analysis",
        provider: "365 Data Science",
        platform: "Udemy",
        url: "https://www.udemy.com/course/statistics-for-data-science-and-business-analysis/",
        level: "Beginner",
        duration: "9 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Introduction to Statistics",
        provider: "Stanford University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/stanford-statistics",
        level: "Beginner",
        duration: "9 weeks",
        free: false,
      },
      {
        title: "Statistics and Data Science MicroMasters",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/micromasters/mitx-statistics-and-data-science",
        level: "Advanced",
        duration: "1 year",
        free: false,
        badge: "Certification",
      },
    ],
  },

  "Data Visualization": {
    description:
      "Data visualization is the art of translating data into clear, compelling charts and dashboards.",
    courses: [
      {
        title: "Data Visualization with Tableau Specialization",
        provider: "UC Davis",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/data-visualization",
        level: "Beginner",
        duration: "5 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Tableau 2024 A-Z: Hands-On Tableau Training for Data Science",
        provider: "Kirill Eremenko",
        platform: "Udemy",
        url: "https://www.udemy.com/course/tableau10/",
        level: "Beginner",
        duration: "9 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Data Analysis and Visualization Foundations",
        provider: "IBM",
        platform: "edX",
        url: "https://www.edx.org/professional-certificate/ibm-data-analysis-and-visualization-foundations",
        level: "Beginner",
        duration: "5 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Matplotlib Crash Course",
        provider: "Keith Galli",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=3Xc3CA655Y4",
        level: "Beginner",
        duration: "1 hour",
        free: true,
        badge: "Free",
      },
      {
        title: "Applied Data Science with Python Specialization",
        provider: "University of Michigan",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/data-science-python",
        level: "Intermediate",
        duration: "5 months",
        free: false,
      },
    ],
  },

  Excel: {
    description:
      "Microsoft Excel is the world's most widely-used spreadsheet tool, core to finance, business analysis, and reporting.",
    courses: [
      {
        title: "Excel Skills for Business Specialization",
        provider: "Macquarie University",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/excel",
        level: "Beginner",
        duration: "6 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Microsoft Excel – Excel from Beginner to Advanced",
        provider: "Kyle Pew",
        platform: "Udemy",
        url: "https://www.udemy.com/course/microsoft-excel-2013-from-beginner-to-advanced-and-beyond/",
        level: "Beginner",
        duration: "19 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Excel for Everyone: Core Foundations",
        provider: "University of British Columbia",
        platform: "edX",
        url: "https://www.edx.org/learn/excel/the-university-of-british-columbia-excel-for-everyone-core-foundations",
        level: "Beginner",
        duration: "6 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Excel Tutorial for Beginners",
        provider: "Kevin Stratvert",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=rwbho0CgEAI",
        level: "Beginner",
        duration: "1.5 hours",
        free: true,
        badge: "Beginner Friendly",
      },
      {
        title: "Financial Analysis with Excel",
        provider: "Corporate Finance Institute",
        platform: "Other",
        url: "https://corporatefinanceinstitute.com/course/excel-fundamentals-formulas-for-finance/",
        level: "Intermediate",
        duration: "6 hours",
        free: false,
      },
    ],
  },

  "Machine Learning": {
    description:
      "Machine learning enables computers to learn from data and make predictions — the engine behind modern AI.",
    courses: [
      {
        title: "Machine Learning Specialization",
        provider: "Andrew Ng / Stanford",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/machine-learning-introduction",
        level: "Intermediate",
        duration: "3 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Machine Learning A-Z: AI, Python & R + ChatGPT Bonus",
        provider: "Kirill Eremenko & Hadelin de Ponteves",
        platform: "Udemy",
        url: "https://www.udemy.com/course/machinelearning/",
        level: "Intermediate",
        duration: "44 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Machine Learning with Python",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/machine-learning-with-python",
        level: "Intermediate",
        duration: "6 weeks",
        free: false,
      },
      {
        title: "Professional Certificate in Machine Learning and Artificial Intelligence",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/professional-certificate/machine-learning-and-artificial-intelligence",
        level: "Advanced",
        duration: "6 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Machine Learning Course – Full Tutorial",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=NWONeJKn6kc",
        level: "Beginner",
        duration: "10 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Deep Learning": {
    description:
      "Deep learning uses neural networks to solve complex problems in vision, language, and speech.",
    courses: [
      {
        title: "Deep Learning Specialization",
        provider: "deeplearning.ai / Andrew Ng",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/deep-learning",
        level: "Intermediate",
        duration: "5 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "PyTorch for Deep Learning Bootcamp",
        provider: "Jose Portilla",
        platform: "Udemy",
        url: "https://www.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/",
        level: "Intermediate",
        duration: "17 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Deep Learning Fundamentals with Keras",
        provider: "IBM",
        platform: "edX",
        url: "https://www.edx.org/learn/deep-learning/ibm-deep-learning-fundamentals-with-keras",
        level: "Intermediate",
        duration: "5 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Neural Networks: Zero to Hero",
        provider: "Andrej Karpathy",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
        level: "Advanced",
        duration: "10+ hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Practical Deep Learning for Coders",
        provider: "fast.ai",
        platform: "Other",
        url: "https://course.fast.ai/",
        level: "Intermediate",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Cloud Computing": {
    description:
      "Cloud computing delivers computing services over the internet — essential for scalable, modern tech infrastructure.",
    courses: [
      {
        title: "Google Cloud Professional Data Engineer",
        provider: "Google Cloud",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/gcp-data-engineering",
        level: "Advanced",
        duration: "6 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "AWS Cloud Practitioner Essentials",
        provider: "Amazon Web Services",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/aws-cloud-practitioner-essentials",
        level: "Beginner",
        duration: "6 hours",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Cloud Computing Fundamentals",
        provider: "IBM",
        platform: "edX",
        url: "https://www.edx.org/learn/cloud-computing/ibm-cloud-computing-fundamentals",
        level: "Beginner",
        duration: "6 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Microsoft Azure Fundamentals (AZ-900)",
        provider: "Microsoft",
        platform: "Udemy",
        url: "https://www.udemy.com/course/az900-azure/",
        level: "Beginner",
        duration: "8 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Cloud Computing Full Course",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=M988_fsOSWo",
        level: "Beginner",
        duration: "11 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  JavaScript: {
    description:
      "JavaScript is the language of the web, powering interactive frontends, backends (Node.js), and full-stack apps.",
    courses: [
      {
        title: "The Complete JavaScript Course 2024: From Zero to Expert!",
        provider: "Jonas Schmedtmann",
        platform: "Udemy",
        url: "https://www.udemy.com/course/the-complete-javascript-course/",
        level: "Beginner",
        duration: "69 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "JavaScript Algorithms and Data Structures",
        provider: "freeCodeCamp",
        platform: "Other",
        url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
        level: "Beginner",
        duration: "300 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Full-Stack Web Development with React Specialization",
        provider: "Hong Kong University of Science",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/full-stack-react",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "JavaScript – Full Course for Beginners",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
        level: "Beginner",
        duration: "3.5 hours",
        free: true,
        badge: "Beginner Friendly",
      },
      {
        title: "CS50's Web Programming with Python and JavaScript",
        provider: "Harvard",
        platform: "edX",
        url: "https://www.edx.org/learn/web-development/harvard-university-cs50-s-web-programming-with-python-and-javascript",
        level: "Intermediate",
        duration: "12 weeks",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Data Structures": {
    description:
      "Data structures and algorithms are the foundation of efficient software engineering and technical interviews.",
    courses: [
      {
        title: "Data Structures and Algorithms Specialization",
        provider: "UC San Diego",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/data-structures-algorithms",
        level: "Intermediate",
        duration: "8 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Master the Coding Interview: Data Structures + Algorithms",
        provider: "Andrei Neagoie",
        platform: "Udemy",
        url: "https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/",
        level: "Intermediate",
        duration: "19.5 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Algorithms and Data Structures",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/course/algorithms-and-data-structures",
        level: "Intermediate",
        duration: "13 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Data Structures Easy to Advanced Course",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=RBSGKlAvoiM",
        level: "Beginner",
        duration: "8 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  DevOps: {
    description:
      "DevOps combines development and operations practices to shorten the development lifecycle and enable continuous delivery.",
    courses: [
      {
        title: "DevOps on AWS Specialization",
        provider: "Amazon Web Services",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/aws-devops",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "DevOps Beginners to Advanced with Projects",
        provider: "Imran Teli",
        platform: "Udemy",
        url: "https://www.udemy.com/course/devsecops/",
        level: "Beginner",
        duration: "36 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Introduction to DevOps",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/intro-to-devops",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "DevOps Engineering Course for Beginners",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=j5Zsa_eOXeY",
        level: "Beginner",
        duration: "2 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Network Security": {
    description:
      "Network security protects computer networks from intruders, whether targeted attackers or opportunistic malware.",
    courses: [
      {
        title: "Google Cybersecurity Professional Certificate",
        provider: "Google",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/google-cybersecurity",
        level: "Beginner",
        duration: "6 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "The Complete Cyber Security Course: Network Security",
        provider: "Nathan House",
        platform: "Udemy",
        url: "https://www.udemy.com/course/network-security-course/",
        level: "Intermediate",
        duration: "12 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Introduction to Cybersecurity",
        provider: "NYU",
        platform: "edX",
        url: "https://www.edx.org/professional-certificate/introduction-to-cybersecurity",
        level: "Beginner",
        duration: "6 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Network Security Full Course",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=E03gh1huvW4",
        level: "Beginner",
        duration: "8 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Cloud Security": {
    description:
      "Cloud security covers the policies, technologies, and controls that protect cloud data, apps, and infrastructure.",
    courses: [
      {
        title: "Security in Google Cloud Specialization",
        provider: "Google Cloud",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/security-google-cloud-platform",
        level: "Advanced",
        duration: "2 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "AWS Security Fundamentals",
        provider: "Amazon Web Services",
        platform: "Other",
        url: "https://explore.skillbuilder.aws/learn/course/48/aws-security-fundamentals",
        level: "Beginner",
        duration: "6 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Cloud Security Basics",
        provider: "University of Minnesota",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/cloud-security-basics",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Cloud Security Full Course",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=cGWN6oeaqDY",
        level: "Beginner",
        duration: "7 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Cryptography: {
    description:
      "Cryptography is the practice of secure communication — underpinning blockchain, HTTPS, and cybersecurity.",
    courses: [
      {
        title: "Cryptography I",
        provider: "Stanford University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/crypto",
        level: "Advanced",
        duration: "7 weeks",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Cryptography and Hashing Overview",
        provider: "University of Colorado",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/cryptography-and-hashing-overview",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
      },
      {
        title: "Blockchain and Cryptocurrency Explained",
        provider: "University of Michigan",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/crypto-finance",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Cryptography Full Course",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=AQDCe585Lnc",
        level: "Intermediate",
        duration: "11 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Operating Systems": {
    description:
      "Operating systems manage hardware and software resources — critical knowledge for systems engineers and developers.",
    courses: [
      {
        title: "Introduction to Operating Systems",
        provider: "Georgia Tech",
        platform: "Udemy",
        url: "https://www.udemy.com/course/introduction-to-operating-systems/",
        level: "Intermediate",
        duration: "7 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Operating Systems: Three Easy Pieces",
        provider: "University of Wisconsin",
        platform: "Other",
        url: "https://pages.cs.wisc.edu/~remzi/OSTEP/",
        level: "Intermediate",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Linux and Private Cloud Administration",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/ibm-linux-private-cloud",
        level: "Intermediate",
        duration: "4 months",
        free: false,
      },
      {
        title: "Operating System Concepts Full Course",
        provider: "Neso Academy",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O",
        level: "Intermediate",
        duration: "20+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Solidity: {
    description:
      "Solidity is the primary programming language for writing smart contracts on Ethereum and EVM-compatible blockchains.",
    courses: [
      {
        title: "Blockchain Specialization",
        provider: "University at Buffalo",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/blockchain",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Ethereum and Solidity: The Complete Developer's Guide",
        provider: "Stephen Grider",
        platform: "Udemy",
        url: "https://www.udemy.com/course/ethereum-and-solidity-the-complete-developers-guide/",
        level: "Intermediate",
        duration: "24 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Solidity Tutorial – A Full Course on Ethereum",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=ipwxYa-F1uY",
        level: "Beginner",
        duration: "16 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "CryptoZombies – Learn Solidity by Building Games",
        provider: "CryptoZombies",
        platform: "Other",
        url: "https://cryptozombies.io/",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Beginner Friendly",
      },
    ],
  },

  "Distributed Systems": {
    description:
      "Distributed systems enable computing across multiple machines — the backbone of cloud, blockchain, and large-scale apps.",
    courses: [
      {
        title: "Cloud Computing Specialization",
        provider: "University of Illinois",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/cloud-computing",
        level: "Advanced",
        duration: "6 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Distributed Systems in One Lesson",
        provider: "Tim Berglund",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=Y6Ev8GIlbxc",
        level: "Intermediate",
        duration: "1 hour",
        free: true,
        badge: "Free",
      },
      {
        title: "MIT 6.824: Distributed Systems",
        provider: "MIT OpenCourseWare",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLrw6a1wE39_tb2fErI4-WkMbsvGQk9_UB",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
    ],
  },

  Linux: {
    description:
      "Linux is the dominant operating system for servers, cloud, and DevOps — a must-have skill for engineers.",
    courses: [
      {
        title: "Linux Fundamentals",
        provider: "The Linux Foundation",
        platform: "edX",
        url: "https://www.edx.org/learn/linux/the-linux-foundation-introduction-to-linux",
        level: "Beginner",
        duration: "14 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Linux Command Line Basics",
        provider: "Ubuntu",
        platform: "Udemy",
        url: "https://www.udemy.com/course/linux-command-line-volume1/",
        level: "Beginner",
        duration: "6 hours",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "The Linux Command Line Bootcamp",
        provider: "Colt Steele",
        platform: "Udemy",
        url: "https://www.udemy.com/course/the-linux-command-line-bootcamp/",
        level: "Beginner",
        duration: "17 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Linux Full Course",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=sWbUDq4S6Y8",
        level: "Beginner",
        duration: "6 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Networking: {
    description:
      "Networking covers how computers communicate — from TCP/IP to routing protocols and network architecture.",
    courses: [
      {
        title: "The Bits and Bytes of Computer Networking",
        provider: "Google",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/computer-networking",
        level: "Beginner",
        duration: "6 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "CompTIA Network+ (N10-008) Full Course",
        provider: "Professor Messer",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=As6g6IXcVa4",
        level: "Intermediate",
        duration: "15 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Cisco CCNA 200-301 Complete Course",
        provider: "David Bombal",
        platform: "Udemy",
        url: "https://www.udemy.com/course/complete-networking-fundamentals-course-ccna-start/",
        level: "Intermediate",
        duration: "79 hours",
        free: false,
        badge: "Top Rated",
      },
    ],
  },

  "Data Pipelines": {
    description:
      "Data pipelines automate the flow of data from source to destination — core to data engineering.",
    courses: [
      {
        title: "Data Engineering Professional Certificate",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/ibm-data-engineer",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Apache Airflow: The Hands-On Guide",
        provider: "Marc Lamberti",
        platform: "Udemy",
        url: "https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow/",
        level: "Intermediate",
        duration: "12 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Fundamentals of Data Engineering",
        provider: "DeepLearning.AI",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/data-engineering-fundamentals",
        level: "Intermediate",
        duration: "3 months",
        free: false,
      },
      {
        title: "Apache Kafka Tutorial",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=SqVfCyfCJqw",
        level: "Intermediate",
        duration: "4 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Spark/Big Data": {
    description:
      "Apache Spark and big data tools enable processing of massive datasets at scale.",
    courses: [
      {
        title: "IBM Data Engineering Professional Certificate",
        provider: "IBM",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/ibm-data-engineer",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Apache Spark with Python – Big Data with PySpark",
        provider: "Jose Portilla",
        platform: "Udemy",
        url: "https://www.udemy.com/course/spark-and-python-for-big-data-with-pyspark/",
        level: "Intermediate",
        duration: "12 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Big Data Specialization",
        provider: "UC San Diego",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/big-data",
        level: "Intermediate",
        duration: "6 months",
        free: false,
      },
      {
        title: "Apache Spark Tutorial | Spark Tutorial for Beginners",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=9mELEARcxJo",
        level: "Beginner",
        duration: "5 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  // ── Business & Finance Skills ──────────────────────────────────────────────

  "Financial Modeling": {
    description:
      "Financial modeling builds spreadsheet-based representations of a company's finances to guide business decisions.",
    courses: [
      {
        title: "Financial Modeling & Valuation Analyst (FMVA)",
        provider: "Corporate Finance Institute",
        platform: "Other",
        url: "https://corporatefinanceinstitute.com/certifications/financial-modeling-valuation-analyst-fmva-program/",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
        badge: "Certification",
      },
      {
        title: "Financial Modeling for Business Decisions",
        provider: "Macquarie University",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/financial-modeling-business-decisions",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Excel & Financial Modeling Fundamentals",
        provider: "Wall Street Prep",
        platform: "Other",
        url: "https://www.wallstreetprep.com/self-study-programs/excel-crash-course/",
        level: "Intermediate",
        duration: "10 hours",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Financial Modeling for Beginners",
        provider: "Corporate Finance Institute",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=mO3r68j6SQk",
        level: "Beginner",
        duration: "1 hour",
        free: true,
        badge: "Free",
      },
    ],
  },

  Accounting: {
    description:
      "Accounting is the systematic recording of financial transactions — essential for finance and business roles.",
    courses: [
      {
        title: "Introduction to Financial Accounting",
        provider: "Wharton School / UPenn",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/wharton-accounting",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Accounting Fundamentals",
        provider: "Corporate Finance Institute",
        platform: "Other",
        url: "https://corporatefinanceinstitute.com/course/learn-accounting-fundamentals-corporate-finance/",
        level: "Beginner",
        duration: "3 hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Accounting & Finance Certificate",
        provider: "edX / Various Universities",
        platform: "edX",
        url: "https://www.edx.org/learn/accounting",
        level: "Beginner",
        duration: "Self-paced",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Accounting Basics Full Course",
        provider: "Accounting Stuff",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=yYX4bvQSqbo",
        level: "Beginner",
        duration: "3 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Tax Law": {
    description:
      "Tax law covers the rules governing how individuals and businesses are taxed — critical for accountants and auditors.",
    courses: [
      {
        title: "Taxation of Business Entities",
        provider: "University of Illinois",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/taxation-business-entities-part-1",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "U.S. Federal Taxation Specialization",
        provider: "University of Illinois",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/united-states-federal-tax",
        level: "Intermediate",
        duration: "5 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Introduction to Tax Law",
        provider: "Various",
        platform: "edX",
        url: "https://www.edx.org/learn/tax-law",
        level: "Beginner",
        duration: "Self-paced",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Tax Basics Explained",
        provider: "Accounting Stuff",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=OFDHmZ0sYaY",
        level: "Beginner",
        duration: "30 mins",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Financial Reporting": {
    description:
      "Financial reporting involves preparing financial statements — the language of business performance.",
    courses: [
      {
        title: "Financial Reporting Specialization",
        provider: "University of Illinois",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/financial-reporting",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Introduction to Financial Accounting",
        provider: "Wharton School / UPenn",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/wharton-accounting",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Understanding Financial Statements",
        provider: "Accounting Stuff",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=WEDIj9JBTC8",
        level: "Beginner",
        duration: "2 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Risk Management": {
    description:
      "Risk management identifies, assesses, and controls threats to an organisation's capital and earnings.",
    courses: [
      {
        title: "Risk Management Professional Certificate",
        provider: "New York Institute of Finance",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/risk-management",
        level: "Intermediate",
        duration: "3 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Financial Risk Management",
        provider: "Various",
        platform: "edX",
        url: "https://www.edx.org/learn/risk-management",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
        badge: "Popular",
      },
      {
        title: "Risk Management for Projects",
        provider: "University of Adelaide",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/risk-management-project",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Risk Management Explained",
        provider: "365 Financial Analyst",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=F2n_-t3YDYQ",
        level: "Beginner",
        duration: "1 hour",
        free: true,
        badge: "Free",
      },
    ],
  },

  Compliance: {
    description:
      "Compliance ensures organisations adhere to laws, regulations, and ethical standards — essential for audit and finance.",
    courses: [
      {
        title: "Regulatory Compliance",
        provider: "Thomson Reuters",
        platform: "Other",
        url: "https://legal.thomsonreuters.com/en/products/compliance-management",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
        badge: "Certification",
      },
      {
        title: "Introduction to Compliance",
        provider: "Various",
        platform: "Coursera",
        url: "https://www.coursera.org/search?query=compliance",
        level: "Beginner",
        duration: "Self-paced",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Governance, Risk, and Compliance (GRC) Explained",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=W_dpCcW5Myw",
        level: "Beginner",
        duration: "1 hour",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Requirements Analysis": {
    description:
      "Requirements analysis defines what a system must do — the bridge between business stakeholders and technical teams.",
    courses: [
      {
        title: "Business Analysis & Process Management",
        provider: "Coursera Project Network",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/business-analysis-process-management",
        level: "Beginner",
        duration: "2 hours",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Agile Meets Design Thinking",
        provider: "University of Virginia",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/uva-darden-getting-started-agile",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Business Analyst Training for Beginners",
        provider: "Intellipaat",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=9Ri4PkXgMqg",
        level: "Beginner",
        duration: "4 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Mathematics: {
    description:
      "Mathematics underpins engineering, AI, finance, and science — from calculus to linear algebra.",
    courses: [
      {
        title: "Mathematics for Machine Learning Specialization",
        provider: "Imperial College London",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/mathematics-machine-learning",
        level: "Intermediate",
        duration: "5 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Calculus 1",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/math/calculus-1",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Linear Algebra",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/math/linear-algebra",
        level: "Intermediate",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Mathematics for Engineers Specialization",
        provider: "Hong Kong UST",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/mathematics-engineers",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "Essence of Calculus",
        provider: "3Blue1Brown",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",
        level: "Beginner",
        duration: "3 hours",
        free: true,
        badge: "Beginner Friendly",
      },
    ],
  },

  // ── Engineering Skills ─────────────────────────────────────────────────────

  CAD: {
    description:
      "Computer-Aided Design (CAD) software creates precise drawings and models used across engineering disciplines.",
    courses: [
      {
        title: "AutoCAD Fundamentals",
        provider: "Autodesk",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/autocad-fundamentals",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Autodesk Fusion 360 Integrated CAD/CAM/CAE",
        provider: "Autodesk",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/autodesk-cad-cam-cae-fusion360",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "Complete AutoCAD 2024 Course",
        provider: "Udemy",
        platform: "Udemy",
        url: "https://www.udemy.com/course/autocad-2d-and-3d-practice-drawings/",
        level: "Beginner",
        duration: "14 hours",
        free: false,
      },
      {
        title: "AutoCAD Tutorial for Beginners",
        provider: "CAD CAM Tutorial",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=VtLXMDKnKFQ",
        level: "Beginner",
        duration: "3 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Structural Analysis": {
    description:
      "Structural analysis determines how structures respond to loads — core to civil and mechanical engineering.",
    courses: [
      {
        title: "A Hands-on Introduction to Engineering Simulations",
        provider: "Cornell University",
        platform: "edX",
        url: "https://www.edx.org/learn/engineering/cornell-university-a-hands-on-introduction-to-engineering-simulations",
        level: "Intermediate",
        duration: "5 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Structural Engineering",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/1-050-solid-mechanics-fall-2004/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Structural Analysis with SAP2000",
        provider: "Udemy",
        platform: "Udemy",
        url: "https://www.udemy.com/courses/search/?q=structural+analysis",
        level: "Intermediate",
        duration: "10 hours",
        free: false,
        badge: "Popular",
      },
    ],
  },

  "Project Management": {
    description:
      "Project management involves planning, executing, and closing projects on time and within budget.",
    courses: [
      {
        title: "Google Project Management Professional Certificate",
        provider: "Google",
        platform: "Coursera",
        url: "https://www.coursera.org/professional-certificates/google-project-management",
        level: "Beginner",
        duration: "6 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "PMP Exam Prep: Project Management Professional",
        provider: "Andrew Ramdayal",
        platform: "Udemy",
        url: "https://www.udemy.com/course/pmp-pmbok6-exam/",
        level: "Advanced",
        duration: "23 hours",
        free: false,
        badge: "Popular",
      },
      {
        title: "Project Management Principles and Practices",
        provider: "UC Irvine",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/project-management",
        level: "Beginner",
        duration: "4 months",
        free: false,
      },
      {
        title: "Project Management Full Course",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=uf2oAK5ZfKo",
        level: "Beginner",
        duration: "8 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Geotechnics: {
    description:
      "Geotechnics studies the behaviour of earth materials — foundations of civil engineering construction.",
    courses: [
      {
        title: "Geotechnical Engineering",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/1-322-soil-behavior-fall-2005/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Ground Engineering – Geotechnics",
        provider: "Various",
        platform: "edX",
        url: "https://www.edx.org/search?q=geotechnics",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
      },
      {
        title: "Geotechnical Engineering Full Course",
        provider: "NPTEL",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLbRMhDVUMngeVrxtNPQ5eE8M1BG2Tq3qU",
        level: "Intermediate",
        duration: "40+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  Thermodynamics: {
    description:
      "Thermodynamics governs energy transfer and transformation — fundamental to mechanical and chemical engineering.",
    courses: [
      {
        title: "Engineering Thermodynamics",
        provider: "UNSW Sydney",
        platform: "edX",
        url: "https://www.edx.org/learn/thermodynamics",
        level: "Intermediate",
        duration: "10 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Thermodynamics Course",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/2-006-thermal-fluids-engineering-ii-spring-2008/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Engineering Thermodynamics and Fluid Mechanics",
        provider: "Georgia Tech",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/engineering-thermodynamics",
        level: "Intermediate",
        duration: "8 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Thermodynamics Full Course",
        provider: "Neso Academy",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLBlnK6fEyqRgJU3EsOYDTW7m6SUmW6kII",
        level: "Beginner",
        duration: "20+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Materials Science": {
    description:
      "Materials science studies the properties of matter to engineer new materials for specific applications.",
    courses: [
      {
        title: "Materials Science: 10 Things Every Engineer Should Know",
        provider: "UC Davis",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/materials-science",
        level: "Beginner",
        duration: "6 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Introduction to Materials Science and Engineering",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/",
        level: "Intermediate",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Materials Science & Engineering Course",
        provider: "NPTEL",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLbRMhDVUMngf-net-VNS3aqtTvBNNtPhw",
        level: "Intermediate",
        duration: "30+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Fluid Mechanics": {
    description:
      "Fluid mechanics studies the behaviour of liquids and gases — essential for mechanical, civil, and chemical engineering.",
    courses: [
      {
        title: "A Hands-On Introduction to Engineering Simulations",
        provider: "Cornell University",
        platform: "edX",
        url: "https://www.edx.org/learn/engineering/cornell-university-a-hands-on-introduction-to-engineering-simulations",
        level: "Intermediate",
        duration: "5 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Fluid Mechanics",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/2-20-marine-hydrodynamics-13-021-spring-2005/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Fluid Mechanics Full Course",
        provider: "Neso Academy",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLBlnK6fEyqRjNtXFzpnqKj8rcQ3RpsPeX",
        level: "Intermediate",
        duration: "25+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Circuit Design": {
    description:
      "Circuit design involves creating electronic circuits for power, signal processing, and computation.",
    courses: [
      {
        title: "Electronic Circuit Design",
        provider: "Georgia Tech",
        platform: "edX",
        url: "https://www.edx.org/professional-certificate/gtx-electronic-circuit-design",
        level: "Intermediate",
        duration: "4 months",
        free: false,
        badge: "Certification",
      },
      {
        title: "Introduction to Electronics",
        provider: "Georgia Tech",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/intro-electronics",
        level: "Beginner",
        duration: "5 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Circuit Design & PCB Layout Tutorial",
        provider: "Robert Feranec",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=QLZKyatqOBo",
        level: "Intermediate",
        duration: "5 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Signal Processing": {
    description:
      "Signal processing analyses and manipulates signals to extract information or improve communication.",
    courses: [
      {
        title: "Digital Signal Processing",
        provider: "EPFL",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/digital-signal-processing",
        level: "Advanced",
        duration: "4 months",
        free: false,
        badge: "Top Rated",
      },
      {
        title: "DSP – Digital Signal Processing",
        provider: "Rutgers University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/dsp",
        level: "Advanced",
        duration: "8 weeks",
        free: false,
      },
      {
        title: "Signal Processing Crash Course",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=-FHm2pQmiSM",
        level: "Intermediate",
        duration: "2 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Embedded Systems": {
    description:
      "Embedded systems are computing systems built into larger devices — from medical equipment to smart appliances.",
    courses: [
      {
        title: "Introduction to Embedded Systems Software and Development Environments",
        provider: "University of Colorado Boulder",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/introduction-embedded-systems",
        level: "Intermediate",
        duration: "5 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Embedded Systems – Shape the World",
        provider: "UT Austin",
        platform: "edX",
        url: "https://www.edx.org/learn/embedded-systems/the-university-of-texas-at-austin-embedded-systems-shape-the-world-microcontroller-input-output",
        level: "Intermediate",
        duration: "16 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Raspberry Pi for Beginners",
        provider: "freeCodeCamp",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=wp3tNv2hSmE",
        level: "Beginner",
        duration: "3 hours",
        free: true,
        badge: "Beginner Friendly",
      },
    ],
  },

  Chemistry: {
    description:
      "Chemistry studies matter and its transformations — foundational for chemical and biomedical engineering.",
    courses: [
      {
        title: "Chemistry of Life",
        provider: "Duke University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/chemistry-of-life",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Beginner Friendly",
      },
      {
        title: "Introduction to Chemistry: Reactions and Ratios",
        provider: "Duke University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/intro-chemistry",
        level: "Beginner",
        duration: "5 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "High School Chemistry",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/science/chemistry",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "MIT 5.111 Principles of Chemical Science",
        provider: "MIT OpenCourseWare",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLUl4u3cNGP61-MXzD-TgTicBPtRUa2cAV",
        level: "Intermediate",
        duration: "30+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Process Engineering": {
    description:
      "Process engineering designs, operates, and optimises chemical and industrial processes at scale.",
    courses: [
      {
        title: "Chemical Process Design",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/10-490-integrated-chemical-engineering-topics-i-introduction-to-biocatalysis-fall-2004/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Process Engineering Course",
        provider: "NPTEL",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLbRMhDVUMngdRzWf8hJ_ZeqXz3dKBDEwi",
        level: "Intermediate",
        duration: "30+ hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Chemical Engineering Fundamentals",
        provider: "Various",
        platform: "edX",
        url: "https://www.edx.org/search?q=chemical+engineering",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
        badge: "Popular",
      },
    ],
  },

  "Operations Research": {
    description:
      "Operations research uses mathematical models and optimisation to improve decision-making in complex systems.",
    courses: [
      {
        title: "Operations Research",
        provider: "TU Delft",
        platform: "edX",
        url: "https://www.edx.org/learn/operations-research/delft-university-of-technology-operations-research",
        level: "Intermediate",
        duration: "8 weeks",
        free: true,
        badge: "Free",
      },
      {
        title: "Supply Chain Management & Operations",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/micromasters/mitx-supply-chain-management",
        level: "Advanced",
        duration: "1 year",
        free: false,
        badge: "Certification",
      },
      {
        title: "Operations Research Course",
        provider: "NPTEL",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLbRMhDVUMnge4jKo5PkEqxQoNJkGj-IKD",
        level: "Intermediate",
        duration: "30+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Supply Chain Management": {
    description:
      "Supply chain management oversees the flow of goods and services from raw material to customer delivery.",
    courses: [
      {
        title: "Supply Chain Management Specialization",
        provider: "Rutgers University",
        platform: "Coursera",
        url: "https://www.coursera.org/specializations/supply-chain-management",
        level: "Intermediate",
        duration: "5 months",
        free: false,
        badge: "Popular",
      },
      {
        title: "MicroMasters in Supply Chain Management",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/micromasters/mitx-supply-chain-management",
        level: "Advanced",
        duration: "1 year",
        free: false,
        badge: "Certification",
      },
      {
        title: "Supply Chain Management Full Course",
        provider: "Simplilearn",
        platform: "YouTube",
        url: "https://www.youtube.com/watch?v=g-5sELmJFJA",
        level: "Beginner",
        duration: "4 hours",
        free: true,
        badge: "Free",
      },
    ],
  },

  "Environmental Science": {
    description:
      "Environmental science examines how human activities impact natural systems and how to protect our planet.",
    courses: [
      {
        title: "The Age of Sustainable Development",
        provider: "Columbia University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/sustainable-development",
        level: "Beginner",
        duration: "10 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Environmental Science",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/science/ap-environmental-science",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Environmental Engineering",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/1-020-ecology-ii-engineering-for-sustainability-spring-2008/",
        level: "Intermediate",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
    ],
  },

  Hydrology: {
    description:
      "Hydrology is the study of the movement, distribution, and management of water on Earth — key to environmental engineering.",
    courses: [
      {
        title: "Global Warming Science",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/search?q=hydrology",
        level: "Intermediate",
        duration: "Self-paced",
        free: false,
      },
      {
        title: "Hydrology Full Course",
        provider: "NPTEL",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PLbRMhDVUMngf4a7XfnXU5M2dZ6lpKfFhF",
        level: "Intermediate",
        duration: "30+ hours",
        free: true,
        badge: "Free",
      },
      {
        title: "Engineering Hydrology",
        provider: "MIT OpenCourseWare",
        platform: "Other",
        url: "https://ocw.mit.edu/courses/1-72-groundwater-hydrology-fall-2005/",
        level: "Advanced",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
    ],
  },

  Biology: {
    description:
      "Biology is the science of life — from cells to ecosystems, it underpins biomedical and environmental engineering.",
    courses: [
      {
        title: "Biology",
        provider: "Khan Academy",
        platform: "Khan Academy",
        url: "https://www.khanacademy.org/science/biology",
        level: "Beginner",
        duration: "Self-paced",
        free: true,
        badge: "Free",
      },
      {
        title: "Introduction to Biology – The Secret of Life",
        provider: "MIT",
        platform: "edX",
        url: "https://www.edx.org/learn/biology/massachusetts-institute-of-technology-introduction-to-biology-the-secret-of-life",
        level: "Beginner",
        duration: "16 weeks",
        free: true,
        badge: "Beginner Friendly",
      },
      {
        title: "Everyday Chemistry",
        provider: "Duke University",
        platform: "Coursera",
        url: "https://www.coursera.org/learn/everyday-chemistry",
        level: "Beginner",
        duration: "4 weeks",
        free: false,
        badge: "Popular",
      },
      {
        title: "Biology Crash Course",
        provider: "CrashCourse",
        platform: "YouTube",
        url: "https://www.youtube.com/playlist?list=PL3EED4C1D684D3ADF",
        level: "Beginner",
        duration: "15+ hours",
        free: true,
        badge: "Free",
      },
    ],
  },
};

// Platform display config
export const PLATFORM_CONFIG: Record<
  Platform,
  { color: string; bg: string; icon: string }
> = {
  Coursera: { color: "text-blue-700", bg: "bg-blue-50 dark:bg-blue-900/20", icon: "school" },
  edX: { color: "text-red-700", bg: "bg-red-50 dark:bg-red-900/20", icon: "account_balance" },
  Udemy: { color: "text-purple-700", bg: "bg-purple-50 dark:bg-purple-900/20", icon: "play_circle" },
  YouTube: { color: "text-red-600", bg: "bg-red-50 dark:bg-red-900/20", icon: "smart_display" },
  "Khan Academy": { color: "text-green-700", bg: "bg-green-50 dark:bg-green-900/20", icon: "auto_stories" },
  "LinkedIn Learning": { color: "text-blue-600", bg: "bg-blue-50 dark:bg-blue-900/20", icon: "work" },
  Other: { color: "text-slate-700", bg: "bg-slate-50 dark:bg-slate-800", icon: "open_in_new" },
};

export const LEVEL_CONFIG = {
  Beginner: { color: "text-green-700 bg-green-100 dark:bg-green-900/30 dark:text-green-300" },
  Intermediate: { color: "text-orange-700 bg-orange-100 dark:bg-orange-900/30 dark:text-orange-300" },
  Advanced: { color: "text-red-700 bg-red-100 dark:bg-red-900/30 dark:text-red-300" },
};
